// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsECvwvatyg9Y0FrGeIRYOHiAQ8nfSDlQ',
    appId: '1:401147925679:web:495063953482293912305a',
    messagingSenderId: '401147925679',
    projectId: 'appalmacen-5e987',
    authDomain: 'appalmacen-5e987.firebaseapp.com',
    storageBucket: 'appalmacen-5e987.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGpze9VroQG46eznYEME0btLXKHS5pXA',
    appId: '1:401147925679:android:535c3643619c5e8112305a',
    messagingSenderId: '401147925679',
    projectId: 'appalmacen-5e987',
    storageBucket: 'appalmacen-5e987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvWRt2cI-tJdURJ8-kuLYTODAZ64NGuz0',
    appId: '1:401147925679:ios:92509cd6fc5d2fe112305a',
    messagingSenderId: '401147925679',
    projectId: 'appalmacen-5e987',
    storageBucket: 'appalmacen-5e987.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvWRt2cI-tJdURJ8-kuLYTODAZ64NGuz0',
    appId: '1:401147925679:ios:92509cd6fc5d2fe112305a',
    messagingSenderId: '401147925679',
    projectId: 'appalmacen-5e987',
    storageBucket: 'appalmacen-5e987.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsECvwvatyg9Y0FrGeIRYOHiAQ8nfSDlQ',
    appId: '1:401147925679:web:6e76318ba046538a12305a',
    messagingSenderId: '401147925679',
    projectId: 'appalmacen-5e987',
    authDomain: 'appalmacen-5e987.firebaseapp.com',
    storageBucket: 'appalmacen-5e987.firebasestorage.app',
  );
}
